name: PQC Action
description: Run the Post Quantum Research CodeQL queries and create a CBOM
inputs:
  codeql-version:
    description: CodeQL bundle version
    required: false
    default: v2.22.3
  language:
    description: The language to analyze
    required: true
  external-repository-token:
    description: Access token for PQC repo - not needed when public
    required: true
runs:
  using: composite
  steps:
    - uses: github/codeql-action/init@v2.22.3
      name: CodeQL init
      with:
        languages: ${{ inputs.language }}
        external-repository-token: ${{ inputs.external-repository-token }}
        config: |
          disable-default-queries: true
          queries:
            - uses: pre-quantum-research/PQC-for-Actions/${{ inputs.language }}/src/suites/cbom.qls@main
    - uses: github/codeql-action/autobuild@v2.22.3
      name: CodeQL autobuild
    - uses: github/codeql-action/analyze@v2.22.3
      name: CodeQL analyze
      with:
        category: /pqc:${{ inputs.language }}
        upload: never
        add-snippets: true
        upload-database: false
        output: ./results/
    - uses: actions/upload-artifact@v3
      with:
        name: pqc-results
        path: ./results/
