name: 'PQC Action'
description: 'Run the Post Quantum Research CodeQL queries and create a CBOM'
inputs:
  codeql-version:
    description: 'CodeQL bundle version'
    required: false
    default: '2.22.3'
  language:
    description: 'The language to analyze'
    required: true
runs:
  using: "composite"
  steps:
    - uses: github/codeql-action/init@${{ inputs.codeql-version }}
      name: CodeQL init
      with:
        languages: ${{ inputs.language }}
    - uses: github/codeql-action/autobuild@${{ inputs.codeql-version }}
      name: CodeQL autobuild
    - uses: github/codeql-action/analyze@${{ inputs.codeql-version }}
      name: CodeQL analyze
      with:
        category: "/pqc:${{ matrix.language }}"
