name: PQC Action
description: Run the Post Quantum Research CodeQL queries and create a CBOM
inputs:
  codeql-version:
    description: CodeQL bundle version
    required: false
    default: v2.22.3
  language:
    description: The language to analyze
    required: true
  pqc-pack-read-token:
    description: Access token for PQC query pack read - not needed when public
    required: true
runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      run: |
        echo "::add-mask::${{ inputs.pqc-pack-read-token }}"
        echo "GH_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"
    - name: Download CodeQL DB
      shell: bash
      run: |
        set -ex
        CODEQL_DB_NAME=${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ inputs.language }}-codeql-db.zip
        gh api \
          -H "Accept: application/zip" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/code-scanning/codeql/databases/${{ inputs.language }} >> ${CODEQL_DB_NAME}
        echo "NO_STORED_DB=$?" >> "$GITHUB_ENV"
        if [ $? -eq 0 ]; then
          unzip -q -d database/ ${CODEQL_DB_NAME}
          cd database/*
          mkdir ${{ github.workspace }}/codeql-db
          (shopt -s dotglob; mv * ${{ github.workspace }}/codeql-db)
        fi
    - name: Install latest CodeQL
      shell: bash
      run: |
        set -ex
        gh extensions install github/gh-codeql
        gh codeql download
        GITHUB_TOKEN=${{ inputs.pqc-pack-read-token }} gh codeql pack download pre-quantum-research/python-cryptography
    - name: Create CodeQL DB
      if: env.NO_STORED_DB != 0
      shell: bash
      run: |
        set -ex
        gh codeql database create --language ${{ inputs.language }} ${{ github.workspace }}/codeql-db
    - name: CodeQL analyze
      shell: bash
      run: |
        set -ex
        SARIF_DIR_PATH=${{ github.workspace }}/pqc-results/${{ github.repository }}
        mkdir -p ${SARIF_DIR_PATH}
        gh codeql database analyze ${{ github.workspace }}/codeql-db \
        pre-quantum-research/${{ inputs.language }}-cryptography \
        --output=${SARIF_DIR_PATH}/${{ inputs.language }}.sarif \
        --format=sarif-latest --sarif-add-snippets --sarif-category="/pqc:${{ inputs.language }}"
    - uses: actions/upload-artifact@v3
      with:
        name: pqc-results
        path: ${{ github.workspace }}/pqc-results
