name: PQC Analyze Action
description: Run the Post Quantum Research CodeQL queries and create a CBOM
inputs:
  repositoryNameWithOwner:
    description: The repository to analyze
    required: false
    default: ${{ github.repository }}
  language:
    description: The language to analyze
    required: true
  upload-to-code-scanning:
    description: Whether to upload the results to GitHub Code Scanning
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      run: |
        # Set up environment variables
        IFS=/ read -r REPO_OWNER REPO_NAME <<< ${{ inputs.repositoryNameWithOwner }}
        echo "REPO_OWNER=${REPO_OWNER}" >> "$GITHUB_ENV"
        echo "REPO_NAME=${REPO_NAME}" >> "$GITHUB_ENV"
        echo "GH_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"
        echo "GITHUB_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"
        echo "CODEQL_EXTRACTOR_JAVA_OPTION_BUILDLESS=true" >> "$GITHUB_ENV"
        echo "CODEQL_EXTRACTOR_JAVA_OPTION_BUILDLESS_CLASSPATH_FROM_BUILD_FILES=true" >> "$GITHUB_ENV"
        echo "CODEQL_DB_PATH=${{ github.workspace }}" >> "$GITHUB_ENV"
        echo "CODEQL_DB_ZIP=codeql-db.zip" >> "$GITHUB_ENV"
        echo "CODEQL_RAM=$(awk '/MemTotal/ { printf "%.0f", $2/1024*0.8 }' /proc/meminfo)" >> "$GITHUB_ENV"
        echo "SARIF_DIR_PATH=${{ github.workspace }}/pqc-results/${{ inputs.repositoryNameWithOwner }}" >> "$GITHUB_ENV"
    - name: Find or install CodeQL
      shell: bash
      run: |
        # Find or install CodeQL
        echo "::group::Find or install CodeQL"
        VERSION="$(find "${{ runner.tool_cache }}/CodeQL" -maxdepth 1 -mindepth 1 -type d -print \
          | sort \
          | tail -n 1 \
          | tr -d '\n')"
        if [ -n "${VERSION}" ]
        then
          echo "$VERSION/x64/codeql" >> $GITHUB_PATH
          echo "Using CodeQL at ${VERSION}"
        else
          gh extensions install github/gh-codeql
          gh codeql download
          gh codeql install-stub
        fi
        echo "::endgroup::"
    - name: Download CodeQL DB
      id: download-codeql-db
      shell: bash
      continue-on-error: true
      run: |
        # Download CodeQL database
        echo "::group::Download CodeQL database"
        ! curl -f -L -o ${CODEQL_DB_ZIP} \
          -H "Accept: application/zip" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repositoryNameWithOwner }}/code-scanning/codeql/databases/${{ inputs.language }}"
        if [ -f ${CODEQL_DB_ZIP} ]
        then
          codeql database unbundle "${CODEQL_DB_ZIP}" --target="${CODEQL_DB_PATH}" --name=codeql-db
          ! codeql database upgrade "${CODEQL_DB_PATH}/codeql-db"
          echo "CODEQL_DB_DOWNLOADED=true" >> "$GITHUB_ENV"        
        fi
        echo "::endgroup::"
    - name: Checkout analysis repository
      if: env.CODEQL_DB_DOWNLOADED != 'true'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repositoryNameWithOwner }}
        path: ${{ inputs.repositoryNameWithOwner }}
    - name: Create CodeQL DB
      if: env.CODEQL_DB_DOWNLOADED != 'true'
      shell: bash
      run: |
        # Create CodeQL database
        echo "::group::Create CodeQL database"
        if ! [ -d ${CODEQL_DB_PATH}/codeql-db ]
        then
          mkdir -p "${CODEQL_DB_PATH}/codeql-db"
          cd ${{ github.workspace }}/${{ inputs.repositoryNameWithOwner }}
          SEARCH_RESULTS=$(gh issue list --repo pre-quantum-research/pqc-data \
            --search "${{ inputs.repositoryNameWithOwner }}/${{ inputs.language }}/$(git rev-parse HEAD)" \
            --state open --json id,number,title)
          RESULT_COUNT=$(jq length <<< "${SEARCH_RESULTS}")
          if [[ ${RESULT_COUNT} -eq 0 ]]; then
            gh issue create \
              --repo pre-quantum-research/pqc-data \
              --title ${{ inputs.repositoryNameWithOwner }}/${{ inputs.language }}/$(git rev-parse HEAD) \
              --label analysis-requested \
              --body ""
          elif [[ ${RESULT_COUNT} -eq 1 ]]; then
            ISSUE_NUMBER=$(jq -r ".[0].number" <<< "${SEARCH_RESULTS}")
            gh api \
              --method "POST" \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "/repos/${{ inputs.repositoryNameWithOwner }}/issues/${ISSUE_NUMBER}/reactions" \
              -f content="+1"
          else
            echo "Found multiple issues matching the search criteria"
          fi
          codeql database create --ram=${CODEQL_RAM} --language=${{ inputs.language }} "${CODEQL_DB_PATH}/codeql-db"
        fi
        echo "::endgroup::"
    - name: Analyze CodeQL DB
      shell: bash
      continue-on-error: true
      run: |
        # Analyze CodeQL database
        echo "::group::Analyze CodeQL database"
        codeql pack download pre-quantum-research/${{ inputs.language }}-cryptography 
        mkdir -p ${SARIF_DIR_PATH}
        codeql database analyze ${CODEQL_DB_PATH}/codeql-db \
          pre-quantum-research/${{ inputs.language }}-cryptography \
          --ram=$CODEQL_RAM \
          --output=${SARIF_DIR_PATH}/${{ inputs.language }}.sarif \
          --format=sarifv2.1.0 --sarif-category="PQC:${{ inputs.repositoryNameWithOwner }}/${{ inputs.language }}" \
          --sarif-add-query-help --sarif-add-snippets \
          --timeout=60
        echo "::endgroup::"
    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: pqc-results
        path: ${{ github.workspace }}/pqc-results
    - name: Upload results to Code Scanning
      if: inputs.upload-to-code-scanning == 'true'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ env.SARIF_DIR_PATH }}/${{ inputs.language }}.sarif

