name: PQC Analyze Action
description: Run the Post Quantum Research CodeQL queries and create a CBOM
inputs:
  repository:
    description: The repository to analyze
    required: false
    default: ${{ github.repository }}
  language:
    description: The language to analyze
    required: true
  pqc-pack-read-token:
    description: Access token for PQC query pack read - not needed when public
    required: true
runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash -x {0}
      run: |
        IFS=/ read -r REPO_OWNER REPO_NAME <<< ${{ inputs.repository }}
        echo "REPO_OWNER=${REPO_OWNER}" >> "$GITHUB_ENV"
        echo "REPO_NAME=${REPO_NAME}" >> "$GITHUB_ENV"
        echo "GH_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"
    - name: Install latest CodeQL
      shell: bash -x {0}
      run: |
        gh extensions install github/gh-codeql
        gh codeql download
        GITHUB_TOKEN=${{ inputs.pqc-pack-read-token }} gh codeql pack download pre-quantum-research/python-cryptography        
    - name: Download CodeQL DB
      id: download-codeql-db
      shell: bash -ex {0}
      continue-on-error: true
      run: |
        CODEQL_DB_NAME=${{ env.REPO_OWNER }}-${{ env.REPO_NAME }}-${{ inputs.language }}-codeql-db.zip
        curl -L -o ${CODEQL_DB_NAME} \
          -H "Accept: application/zip" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ inputs.repository }}/code-scanning/codeql/databases/${{ inputs.language }}"
        unzip -q -d database/ ${CODEQL_DB_NAME}
        cd database/*
        mkdir ${{ github.workspace }}/codeql-db
        (shopt -s dotglob; mv * ${{ github.workspace }}/codeql-db)
        gh codeql database upgrade ${{ github.workspace }}/codeql-db
    - name: Create CodeQL DB
      if: ${{ steps.download-codeql-db.outcome }} == "failure"
      shell: bash -x {0}
      run: |
        gh codeql database create --language ${{ inputs.language }} ${{ github.workspace }}/codeql-db
    - name: CodeQL analyze
      shell: bash -x {0}
      run: |
        SARIF_DIR_PATH=${{ github.workspace }}/pqc-results/${{ inputs.repository }}
        mkdir -p ${SARIF_DIR_PATH}
        gh codeql database analyze ${{ github.workspace }}/codeql-db \
        pre-quantum-research/${{ inputs.language }}-cryptography \
        --output=${SARIF_DIR_PATH}/${{ inputs.language }}.sarif \
        --format=sarif-latest --sarif-add-snippets --sarif-category="/pqc:${{ inputs.language }}"
    - uses: actions/upload-artifact@v3
      with:
        name: pqc-results
        path: ${{ github.workspace }}/pqc-results
