name: PQC Analyze Action
description: Run the Post Quantum Research CodeQL queries and create a CBOM
inputs:
  repository:
    description: The repository to analyze
    required: false
    default: ${{ github.repository }}
  language:
    description: The language to analyze
    required: true
  pqc-pack-read-token:
    description: Access token for PQC query pack read - not needed when public
    required: true
runs:
  using: composite
  steps:
    - name: Set up env
      shell: bash
      run: |
        set -x
        IFS=/ read -r REPO_OWNER REPO_NAME <<< ${{ inputs.repository }}
        echo "REPO_OWNER=${REPO_OWNER}" >> "$GITHUB_ENV"
        echo "REPO_NAME=${REPO_NAME}" >> "$GITHUB_ENV"
        echo "GH_TOKEN=${{ github.token }}" >> "$GITHUB_ENV"
    - name: Download CodeQL DB
      shell: bash
      continue-on-error: true
      run: |
        CODEQL_DB_NAME=${{ env.REPO_OWNER }}-${{ env.REPO_NAME }}-${{ inputs.language }}-codeql-db.zip
        gh api \
          -H "Accept: application/zip" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ inputs.repository }}/code-scanning/codeql/databases/${{ inputs.language }} >> ${CODEQL_DB_NAME}
        echo "NO_STORED_DB=$?" >> "$GITHUB_ENV"
        if [ $? -eq 0 ]; then
          unzip -q -d database/ ${CODEQL_DB_NAME}
          cd database/*
          mkdir ${{ github.workspace }}/codeql-db
          (shopt -s dotglob; mv * ${{ github.workspace }}/codeql-db)
        fi
    - name: Install latest CodeQL
      shell: bash
      run: |
        gh extensions install github/gh-codeql
        gh codeql download
        GITHUB_TOKEN=${{ inputs.pqc-pack-read-token }} gh codeql pack download pre-quantum-research/python-cryptography
    - name: Create CodeQL DB
      shell: bash
      run: |
        env
        if [ $NO_STORED_DB -ne 0 ]; then
          gh codeql database create --language ${{ inputs.language }} ${{ github.workspace }}/codeql-db
        fi
    - name: CodeQL analyze
      shell: bash
      run: |
        SARIF_DIR_PATH=${{ github.workspace }}/pqc-results/${{ inputs.repository }}
        mkdir -p ${SARIF_DIR_PATH}
        gh codeql database upgrade ${{ github.workspace }}/codeql-db
        gh codeql database analyze ${{ github.workspace }}/codeql-db \
        pre-quantum-research/${{ inputs.language }}-cryptography \
        --output=${SARIF_DIR_PATH}/${{ inputs.language }}.sarif \
        --format=sarif-latest --sarif-add-snippets --sarif-category="/pqc:${{ inputs.language }}"
    - uses: actions/upload-artifact@v3
      with:
        name: pqc-results
        path: ${{ github.workspace }}/pqc-results
