name: Run PQC

on:
  workflow_dispatch:
  push:
    paths:
      - "**/action.yml"
      - ".github/workflows/pqc.yml"

permissions:
  actions: read
  contents: read
  security-events: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.dep-graph.outputs.repos }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./dep-graph
        id: dep-graph
        with:
          repository: numpy/numpy
  run-pqc-action:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp", "csharp", "go", "java", "python"]
        repository: ${{ fromJSON(needs.build-matrix.outputs.repos) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./analyze
        with:
          repository: ${{ matrix.repository }}
          language: python
          pqc-pack-read-token: ${{ secrets.PQC_FOR_ACTIONS_PACK_READ }}
