name: Run PQC

on:
  workflow_dispatch:
  push:
    paths:
      - "**/action.yml"
      - ".github/workflows/pqc.yml"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix-action.outputs.repositories }}
    steps:
      - uses: actions/checkout@v4
      - uses: pre-quantum-research/pqc-action/build-matrix@main
        id: build-matrix-action
        with:
          repositoryNameWithOwner: ctcampbell/webgoat
          minimumLanguageBytes: 20000
  run-pqc-action:
    runs-on: ubuntu-latest
    needs: build-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pre-quantum-research/pqc-action/analyze@main
        with:
          repositoryNameWithOwner: ${{ fromJson(matrix.repository)[0] }}
          language: ${{ fromJson(matrix.repository)[1] }}
          pqc-pack-read-token: ${{ secrets.PQC_FOR_ACTIONS_PACK_READ }}
  add-workflow-summary:
    runs-on: ubuntu-latest
    needs: run-pqc-action
    steps:
      - uses: actions/checkout@v4
      - uses: pre-quantum-research/pqc-action/workflow-summary@main
