name: Run PQC

on: workflow_dispatch

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  run-pqc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          language: java
          external-repository-token: ${{ secrets.PQC_REPO_ACCESS }}
