name: Run PQC

on:
  workflow_dispatch:
  push:
    paths:
      - action.yml

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  run-pqc-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          language: python
          pqc-pack-read-token: ${{ secrets.PQC_FOR_ACTIONS_PACK_READ }}
