name: Run PQC

on:
  workflow_dispatch:
  push:
    paths:
      - action.yml

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  run-pqc-action:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository: ["${{ github.repository }}", "numpy/numpy", "python/cpython"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          repository: ${{ matrix.repository }}
          language: python
          pqc-pack-read-token: ${{ secrets.PQC_FOR_ACTIONS_PACK_READ }}
