name: Run PQC

on:
  workflow_dispatch:
  push:
    paths:
      - "**/action.yml"
      - ".github/workflows/pqc.yml"

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.build-matrix-action.outputs.repositories }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./build-matrix
        id: build-matrix-action
        with:
          repositoryNameWithOwner: numpy/numpy
  run-pqc-action:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(needs.build-matrix.outputs.repositories) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./analyze
        timeout-minutes: 10
        with:
          repositoryNameWithOwner: ${{ fromJson(matrix.repository)[0] }}
          language: ${{ fromJson(matrix.repository)[1] }}
          pqc-pack-read-token: ${{ secrets.PQC_FOR_ACTIONS_PACK_READ }}
